groups:
  - name: specialized_alerts
    rules:
      # Job Processing Alerts
      - alert: HighJobFailureRate
        expr: |
          sum(rate(job_processing_total{status="failed"}[5m])) by (type, priority)
          /
          sum(rate(job_processing_total[5m])) by (type, priority) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High job failure rate detected"
          description: "Job type {{ $labels.type }} with priority {{ $labels.priority }} has a failure rate above 10%"

      - alert: JobProcessingDelay
        expr: |
          sum(rate(job_processing_total{status="pending"}[5m])) by (type, priority)
          >
          sum(rate(job_processing_total{status="completed"}[5m])) by (type, priority) * 1.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Job processing delay detected"
          description: "Processing rate for {{ $labels.type }} jobs ({{ $labels.priority }}) is 50% slower than completion rate"

      # Service Health Alerts
      - alert: ServiceHealthDegraded
        expr: |
          avg(component_health) by (component) < 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Service health degraded"
          description: "Service {{ $labels.component }} health is below 80%"

      - alert: ServiceDependencyUnhealthy
        expr: |
          dependency_health < 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Service dependency unhealthy"
          description: "Dependency {{ $labels.dependency }} ({{ $labels.type }}) health is below 90%"

      # Data Integrity Alerts
      - alert: DataIntegrityCompromised
        expr: |
          data_integrity_score < 0.95
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Data integrity compromised"
          description: "Data integrity score for {{ $labels.data_type }} is below 95%"

      # Network Performance Alerts
      - alert: HighNetworkLatency
        expr: |
          rate(network_latency_seconds_sum[5m]) / rate(network_latency_seconds_count[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High network latency detected"
          description: "Network latency for {{ $labels.endpoint }} is above 1 second"

      # Error Rate Alerts
      - alert: HighErrorRate
        expr: |
          rate(error_distribution_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate for {{ $labels.error_type }} in {{ $labels.component }} is above 0.1 per second"

      # Queue Health Alerts
      - alert: QueueBacklog
        expr: |
          sum(job_processing_total{status="pending"}) by (type, priority)
          >
          sum(job_processing_total{status="completed"}[1h]) by (type, priority)
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Queue backlog detected"
          description: "Queue for {{ $labels.type }} jobs ({{ $labels.priority }}) has more pending jobs than completed in the last hour"

      # System Resource Alerts
      - alert: HighMemoryUsage
        expr: |
          process_resident_memory_bytes / process_virtual_memory_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Process memory usage is above 80%"

      # Custom Error Pattern Alerts
      - alert: RepeatedErrors
        expr: |
          count_over_time(error_distribution_total{error_type=~"timeout|connection.*"}[5m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Repeated errors detected"
          description: "Multiple {{ $labels.error_type }} errors in {{ $labels.component }} within 5 minutes" 